### ISSUE TITLE
How to generate .simplemap file and rawlog files on my own dataset?

### ISSUE THREAD

**Issue by WilliamWoo45** [mrpt-ros-pkg/mrpt_navigation#105]
Hi all !

I'm trying to implement the **mrpt_localization** (particle filter localization) based on my own data. 
What I have are the **rosbag** file (collect by Husky robot) and **.pgm / .yaml** file (collected by running Hector_SLAM and map_server). 

But after checking the files on [www.mrpt.org](url), I still don't know how to generate the **.simplemap** file and the **.rawlog** file. 
Do you have any advice or commend for this?
Thanks!

@jlblancoc @maxbader

**Comment by felixkoenig** [comment]
Hi, 

use mrpt_navigation/mrpt_rawlog: https://wiki.ros.org/mrpt_rawlog.
The rawlog record node converts the bag file to rawlog format.

For generating a simplemap, you can either use the mrpt_navigation/map_server to convert directly an occupancy gridmap (from ros) to a simplemap or generate a simplemap from your rawlog file via one of the SLAM algorithms in core MRPT, rbpf-slam for instance.

Hope this helps,
Felix
