### ISSUE TITLE
publish mrpt_pose

### ISSUE THREAD

**Issue by sweetquiet** [mrpt-ros-pkg/mrpt_navigation#117]
@jolting Hi!  [pdf_](https://github.com/mrpt-ros-pkg/mrpt_navigation/blob/a9515ad7ef497b395f804c4bfafa75bf541bff8b/mrpt_localization/src/mrpt_localization_node.cpp#L641)

**Comment by jlblancoc** [comment]
Quite a cryptic issue report... but I got it ;-) 
Thanks!
