### ISSUE TITLE
Insert PointCloud2 data instead of laser scan data

### ISSUE THREAD

**Issue by BarzelS** [mrpt-ros-pkg/mrpt_navigation#121]
Is it possible to insert pointcloud2 data to the local obstacles map?
Converting the point cloud to laser scan omits a lot of relevant data
Thanks

**Comment by jlblancoc** [comment]
This is solved now with the [mrpt_pointcloud_pipeline](https://github.com/mrpt-ros-pkg/mrpt_navigation/tree/ros2/mrpt_pointcloud_pipeline) package.
