### ISSUE TITLE
how to switch to a new map when running mrpt_localization_node?

### ISSUE THREAD

**Issue by ZOUJIASHUAI** [mrpt-ros-pkg/mrpt_navigation#123]
is there any demo that I can refer?

**Comment by jlblancoc** [comment]
I think we forgot adding that possibility... 

If someone wants to give a hand, a PR with this feature would be more than welcome! :-)

**Comment by jlblancoc** [comment]
In the new ROS 2 architecture, the map switch is a responsibility of the `mrpt_map` node, not the PF localization node.
Refer to the updated readme (WIP...):
https://github.com/mrpt-ros-pkg/mrpt_navigation/tree/ros2/mrpt_map#working-rationale
