### ISSUE TITLE
Drop dependency on marker_msgs

### ISSUE THREAD

**Issue by jlblancoc** [mrpt-ros-pkg/mrpt_navigation#138]
Build error on the build farm:

    KeyError: 'marker_msgs'

Reason: that package is not released anymore.

Solution: drop the use of that package and replace by any other standard way to send markers to rviz (I think that was it's use). MVSim does that already, for reference.

**Comment by maxbader** [comment]
marker_msgs is allready released for ros2 humble.
But I also understand the reason for dropping the dependeny. We are behind with the rviz2 plugin but it will be released soon as well.

**Comment by jlblancoc** [comment]
Hi @maxbader ! 

Ah, I thought it was not. I'll consider the different options... 

Thanks.

**Comment by jlblancoc** [comment]
PS: as an advice: always release first to rolling. That way, new distros will always already come with a version of your package...

**Comment by jlblancoc** [comment]
@maxbader Ok, I reviewed the code and the only relevant use was in mrpt_msgs_bridge, so I made that code build-dependent to whether marker_msgs is present in the system or not, and commented it out from package.xml. 

Once marker_msgs is available in humble, iron, rolling, feel free of editing/pull-request to uncomment that line from package.xml and it will be included and working again!
