### ISSUE TITLE
mrpt_rawlog build fails for Kinetic

### ISSUE THREAD

**Issue by jacquelinekay** [mrpt-ros-pkg/mrpt_navigation#24]
The binary job fails for several platforms, including Ubuntu Xenial amd64 (our main target):

http://build.ros.org/job/Kbin_uX64__mrpt_rawlog__ubuntu_xenial_amd64__binary/

**Comment by jlblancoc** [comment]
Thanks for notifying! 

It should be fixed with the latest commits earlier today.
