### ISSUE TITLE
mrpt_reactivenav2d compilation fails

### ISSUE THREAD

**Issue by bergercookie** [mrpt-ros-pkg/mrpt_navigation#52]
After having pulled the latest changes from the MRPT master branch as well as the latest changes from this repository, the mrpt_reactivenav2d doesn't compile successfully and produces the following
[error_message](https://github.com/mrpt-ros-pkg/mrpt_navigation/files/632443/error_log.txt)

MRPT Version: 1.5.0
OS: Ubuntu 14.04
ROS Distro: Indigo

**Comment by jlblancoc** [comment]
Thanks,  will fix that soon...
