### ISSUE TITLE
‘THROW_EXCEPTION_CUSTOM_MSG1’ was not declared in this scope

### ISSUE THREAD

**Issue by andrestoga** [mrpt-ros-pkg/mrpt_navigation#60]
Hi,

Trying to compile the code I get the following error:

```
In static member function ‘static const bool mrpt_bridge::MapHdl::loadMap(mrpt::maps::CMultiMetricMap&, const mrpt::utils::CConfigFile&, const string&, const string&, bool)’:
/home/andrestoga/ros_Map_Merging/src/mrpt_navigation/mrpt_bridge/src/map.cpp:201:94: error: ‘THROW_EXCEPTION_CUSTOM_MSG1’ was not declared in this scope
             THROW_EXCEPTION_CUSTOM_MSG1("Map file has unknown extension: '%s'",mapExt.c_str());
```

Best,

**Comment by jlblancoc** [comment]
Hi @andrestoga ! 

This one should have also gone after updating to the PPA, right? 

These are the nuisances of "unstable" versions, sorry!

**Comment by andrestoga** [comment]
Nope, I commented it out and it works after that.

**Comment by majorx234** [comment]
Hi,
have same issue when compiling with mrpt 1.5.
solved it by adding following line in mrpt_bridge/src/map.cpp:
#if MRPT_VERSION>=0x150
#define THROW_EXCEPTION_CUSTOM_MSG1(msg,param1) \ 
THROW_EXCEPTION_FMT(msg,param1)

**Comment by andrestoga** [comment]
Thanks! It works!

**Comment by jlblancoc** [comment]
It's now fixed in master. 
Cheers!
