### ISSUE TITLE
File "kf-slam_demo_2d.rawlog" included in launch file not found

### ISSUE THREAD

**Issue by andrestoga** [mrpt-ros-pkg/mrpt_navigation#71]
Hi,

The file "kf-slam_demo_2d.rawlog" included in launch file "demo_play_ekf_2d.launch" doesn't exist. I wonder what happened to that file.

Best,

**Comment by Logrus** [comment]
Hi @andrestoga,

Thanks for spotting this! You can find the file in [mrpt_slam_ekf_2d/tutorial](https://github.com/mrpt-ros-pkg/mrpt_slam/tree/master/mrpt_icp_slam_2d/tutorial). I also fixed the launch file https://github.com/mrpt-ros-pkg/mrpt_navigation/commit/ccc2586122618a9ad0e235bc8ec980eb14293b5e. 

Hope it helps.

Best,
Vladislav

**Comment by jlblancoc** [comment]
:+1:
