### ISSUE TITLE
Support for .yaml ROS "map_server" maps

### ISSUE THREAD

**Issue by davidbsp** [mrpt-ros-pkg/mrpt_navigation#73]
Is it possible to run mrpt_localization with a known map, using the .yaml format used in map_server package of ROS? I couldn't find information on how to do it.

If it is not possible, how can i generate a .simplemap / .gridmap from a .yaml. file and a bitmap?

**Comment by rsmallegoor** [comment]
I think this is what you are looking for: [image2gridmap](http://www.mrpt.org/list-of-mrpt-apps/application-image2gridmap/)
