### ISSUE TITLE
 MRPT EXCEPTION at "mrpt::math::CRuntimeCompiledExpression::compile"

### ISSUE THREAD

**Issue by lvchaoshun** [mrpt-ros-pkg/mrpt_navigation#89]
**I installed the mrpt-1.5.0 on my Debian 8 & ROS Kinetic.
I compiled the ros_navigation and run the package mrpt_reactiveNav2d on my robot.
But i get MRPT EXCEPTION when send a goal to the node  mrpt_reactiveNav2d:**

[MRPT_navigator|DEBUG|10:04:46.4866] [CAbstractNavigator::navigationStep()] Navigation Params:
navparams. Single target:
target_coords = (2.785,-0.022,-0.014 deg)
target_frame_id = "map"
targetAllowedDistance = 0.400
targetIsRelative = NO
targetIsIntermediaryWaypoint = NO
targetDesiredRelSpeed = 0.05
restrict_PTG_indices: []

=============== MRPT EXCEPTION =============
void mrpt::math::CRuntimeCompiledExpression::compile(const string&, const std::map<std::basic_string<char>, double>&, const string&), line 49:
Error compiling expression (name=`score: collision_free_distance`): `var effective_trg_d_norm := max(0,target_d_norm-move_cur_d); 	if (collision_free_distance>(effective_trg_d_norm+0.05), 		1.0, 		collision_free_distance)`. Error: `ERR186 - Undefined symbol: 'target_d_norm'`
[MRPT_navigator|ERROR|08:43:19.8529] [CAbstractNavigator::navigationStep()] Stoping Navigation due to a NAV_ERROR state!

**sometimes this error:**
 =============== MRPT EXCEPTION =============
int mrpt::nav::CMultiObjectiveMotionOptimizerBase::decide(const std::vector<mrpt::nav::TCandidateMovementPTG>&, mrpt::nav::CMultiObjectiveMotionOptimizerBase::TResultInfo&), line 67:
Error: Expression name `collision_free_distance` already exists as an input variable.
[MRPT_navigator|ERROR|10:27:43.8996] [CAbstractNavigator::navigationStep()] Stoping Navigation due to a NAV_ERROR state!

**Is the mrpt library's problem or is my program configuration problem?**

**Comment by jlblancoc** [comment]
Hi ,

If I recall it right, it was a bug in the MRPT library (module: mrpt-nav) that was fixed (let me check the CHANGELOG...) in MRPT 1.5.2. Please, use MRPT 1.5.4 to see if the error effectively was solved there. 

Best,
