### ISSUE TITLE
CMakeLists.txt of mrpt_bridge doesn't add header files correctly

### ISSUE THREAD

**Issue by majorx234** [mrpt-ros-pkg/mrpt_navigation#91]
in Line: 108 of mrpt_bridge/CMakeLists.txt

`FILES_MATCHING PATTERN "*.h *.hpp"`

should be changed to

`FILES_MATCHING PATTERN "*.h" PATTERN "*.hpp"`

because it installs no headers with this expression

**Comment by jlblancoc** [comment]
Thanks! 👍
