### ISSUE TITLE
Robustify mrpt_* compilation + CI - Build against specific hash of MRPT

### ISSUE THREAD

**Issue by bergercookie** [mrpt-ros-pkg/mrpt_navigation#95]
@jlblancoc 

Up to this point every modification in the API of MRPT classes/methods demanded a respective modifications for the objects that make use of the former in both the mrpt_navigation and mrpt_slam packages. To make the compilation of the latter more stable we can explicitly indicate the MRPT version to be used (either via a tagged version (MRPT-1.5)  or a git-commit) for the CI tests as well as guarantee to the users of the packages that if they use that version the mrpt_* ROS packages will most definitely **just work**.

A rather straightforward  implementation of this is to put a file in the root of the repo (e.g., `MRPT_VERSION` with a line containing that commit. Updating the mrpt version to be used would then be as simple as modifying and committing that specific file.

Thoughts?

**Comment by jlblancoc** [comment]
This repo now only addresses mrpt 2.x.x and hopefully we'll try to keep the API rather stable :-)
